# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ayako/桌面/fqz

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ayako/桌面/fqz

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayako/桌面/fqz/CMakeFiles /home/ayako/桌面/fqz/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ayako/桌面/fqz/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hello

# Build rule for target.
hello: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello
.PHONY : hello

# fast build rule for target.
hello/fast:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/build
.PHONY : hello/fast

#=============================================================================
# Target rules for targets named hello_autogen

# Build rule for target.
hello_autogen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 hello_autogen
.PHONY : hello_autogen

# fast build rule for target.
hello_autogen/fast:
	$(MAKE) -f CMakeFiles/hello_autogen.dir/build.make CMakeFiles/hello_autogen.dir/build
.PHONY : hello_autogen/fast

Clock.o: Clock.cpp.o

.PHONY : Clock.o

# target to build an object file
Clock.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Clock.cpp.o
.PHONY : Clock.cpp.o

Clock.i: Clock.cpp.i

.PHONY : Clock.i

# target to preprocess a source file
Clock.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Clock.cpp.i
.PHONY : Clock.cpp.i

Clock.s: Clock.cpp.s

.PHONY : Clock.s

# target to generate assembly for a file
Clock.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Clock.cpp.s
.PHONY : Clock.cpp.s

Register.o: Register.cpp.o

.PHONY : Register.o

# target to build an object file
Register.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Register.cpp.o
.PHONY : Register.cpp.o

Register.i: Register.cpp.i

.PHONY : Register.i

# target to preprocess a source file
Register.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Register.cpp.i
.PHONY : Register.cpp.i

Register.s: Register.cpp.s

.PHONY : Register.s

# target to generate assembly for a file
Register.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Register.cpp.s
.PHONY : Register.cpp.s

Sign_in.o: Sign_in.cpp.o

.PHONY : Sign_in.o

# target to build an object file
Sign_in.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Sign_in.cpp.o
.PHONY : Sign_in.cpp.o

Sign_in.i: Sign_in.cpp.i

.PHONY : Sign_in.i

# target to preprocess a source file
Sign_in.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Sign_in.cpp.i
.PHONY : Sign_in.cpp.i

Sign_in.s: Sign_in.cpp.s

.PHONY : Sign_in.s

# target to generate assembly for a file
Sign_in.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/Sign_in.cpp.s
.PHONY : Sign_in.cpp.s

hello_autogen/3YJK5W5UP7/qrc_resources.o: hello_autogen/3YJK5W5UP7/qrc_resources.cpp.o

.PHONY : hello_autogen/3YJK5W5UP7/qrc_resources.o

# target to build an object file
hello_autogen/3YJK5W5UP7/qrc_resources.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello_autogen/3YJK5W5UP7/qrc_resources.cpp.o
.PHONY : hello_autogen/3YJK5W5UP7/qrc_resources.cpp.o

hello_autogen/3YJK5W5UP7/qrc_resources.i: hello_autogen/3YJK5W5UP7/qrc_resources.cpp.i

.PHONY : hello_autogen/3YJK5W5UP7/qrc_resources.i

# target to preprocess a source file
hello_autogen/3YJK5W5UP7/qrc_resources.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello_autogen/3YJK5W5UP7/qrc_resources.cpp.i
.PHONY : hello_autogen/3YJK5W5UP7/qrc_resources.cpp.i

hello_autogen/3YJK5W5UP7/qrc_resources.s: hello_autogen/3YJK5W5UP7/qrc_resources.cpp.s

.PHONY : hello_autogen/3YJK5W5UP7/qrc_resources.s

# target to generate assembly for a file
hello_autogen/3YJK5W5UP7/qrc_resources.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello_autogen/3YJK5W5UP7/qrc_resources.cpp.s
.PHONY : hello_autogen/3YJK5W5UP7/qrc_resources.cpp.s

hello_autogen/mocs_compilation.o: hello_autogen/mocs_compilation.cpp.o

.PHONY : hello_autogen/mocs_compilation.o

# target to build an object file
hello_autogen/mocs_compilation.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello_autogen/mocs_compilation.cpp.o
.PHONY : hello_autogen/mocs_compilation.cpp.o

hello_autogen/mocs_compilation.i: hello_autogen/mocs_compilation.cpp.i

.PHONY : hello_autogen/mocs_compilation.i

# target to preprocess a source file
hello_autogen/mocs_compilation.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello_autogen/mocs_compilation.cpp.i
.PHONY : hello_autogen/mocs_compilation.cpp.i

hello_autogen/mocs_compilation.s: hello_autogen/mocs_compilation.cpp.s

.PHONY : hello_autogen/mocs_compilation.s

# target to generate assembly for a file
hello_autogen/mocs_compilation.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/hello_autogen/mocs_compilation.cpp.s
.PHONY : hello_autogen/mocs_compilation.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/main.cpp.s
.PHONY : main.cpp.s

mainClock.o: mainClock.cpp.o

.PHONY : mainClock.o

# target to build an object file
mainClock.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/mainClock.cpp.o
.PHONY : mainClock.cpp.o

mainClock.i: mainClock.cpp.i

.PHONY : mainClock.i

# target to preprocess a source file
mainClock.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/mainClock.cpp.i
.PHONY : mainClock.cpp.i

mainClock.s: mainClock.cpp.s

.PHONY : mainClock.s

# target to generate assembly for a file
mainClock.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/mainClock.cpp.s
.PHONY : mainClock.cpp.s

mainwindow.o: mainwindow.cpp.o

.PHONY : mainwindow.o

# target to build an object file
mainwindow.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/mainwindow.cpp.o
.PHONY : mainwindow.cpp.o

mainwindow.i: mainwindow.cpp.i

.PHONY : mainwindow.i

# target to preprocess a source file
mainwindow.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/mainwindow.cpp.i
.PHONY : mainwindow.cpp.i

mainwindow.s: mainwindow.cpp.s

.PHONY : mainwindow.s

# target to generate assembly for a file
mainwindow.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/mainwindow.cpp.s
.PHONY : mainwindow.cpp.s

start_task.o: start_task.cpp.o

.PHONY : start_task.o

# target to build an object file
start_task.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/start_task.cpp.o
.PHONY : start_task.cpp.o

start_task.i: start_task.cpp.i

.PHONY : start_task.i

# target to preprocess a source file
start_task.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/start_task.cpp.i
.PHONY : start_task.cpp.i

start_task.s: start_task.cpp.s

.PHONY : start_task.s

# target to generate assembly for a file
start_task.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/start_task.cpp.s
.PHONY : start_task.cpp.s

usercenter.o: usercenter.cpp.o

.PHONY : usercenter.o

# target to build an object file
usercenter.cpp.o:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/usercenter.cpp.o
.PHONY : usercenter.cpp.o

usercenter.i: usercenter.cpp.i

.PHONY : usercenter.i

# target to preprocess a source file
usercenter.cpp.i:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/usercenter.cpp.i
.PHONY : usercenter.cpp.i

usercenter.s: usercenter.cpp.s

.PHONY : usercenter.s

# target to generate assembly for a file
usercenter.cpp.s:
	$(MAKE) -f CMakeFiles/hello.dir/build.make CMakeFiles/hello.dir/usercenter.cpp.s
.PHONY : usercenter.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... hello"
	@echo "... hello_autogen"
	@echo "... Clock.o"
	@echo "... Clock.i"
	@echo "... Clock.s"
	@echo "... Register.o"
	@echo "... Register.i"
	@echo "... Register.s"
	@echo "... Sign_in.o"
	@echo "... Sign_in.i"
	@echo "... Sign_in.s"
	@echo "... hello_autogen/3YJK5W5UP7/qrc_resources.o"
	@echo "... hello_autogen/3YJK5W5UP7/qrc_resources.i"
	@echo "... hello_autogen/3YJK5W5UP7/qrc_resources.s"
	@echo "... hello_autogen/mocs_compilation.o"
	@echo "... hello_autogen/mocs_compilation.i"
	@echo "... hello_autogen/mocs_compilation.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mainClock.o"
	@echo "... mainClock.i"
	@echo "... mainClock.s"
	@echo "... mainwindow.o"
	@echo "... mainwindow.i"
	@echo "... mainwindow.s"
	@echo "... start_task.o"
	@echo "... start_task.i"
	@echo "... start_task.s"
	@echo "... usercenter.o"
	@echo "... usercenter.i"
	@echo "... usercenter.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

